### ISSUE TITLE
[Bug]: Target [Illuminate\Contracts\Auth\Access\Gate] is not instantiable. 

### ISSUE THREAD

**Issue by CupNoodles** [tastyigniter/ti-ext-broadcast#8]
### What happened?

Enabling this ext on the current versions throws this error (full stack trace below)

### What did you expect to happen?

I don't know enough about the Laravel stack to add any relevant comments here - it's a fresh installation on 3.3.2 using the 'Install Recommended Extensions' feature.

### Version

3.2.x

### What browser are you seeing the problem on?

Firefox

### Relevant log output

```shell
Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Auth\Access\Gate] is not instantiable.
in /home/okonomi/okonomibk.com/vendor/laravel/framework/src/Illuminate/Container/Container.php:1089
Stack trace:
#0 /home/okonomi/okonomibk.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(886): Illuminate\Container\Container->notInstantiable()
#1 /home/okonomi/okonomibk.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(758): Illuminate\Container\Container->build()
#2 /home/okonomi/okonomibk.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(851): Illuminate\Container\Container->resolve()
#3 /home/okonomi/okonomibk.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(694): Illuminate\Foundation\Application->resolve()
#4 /home/okonomi/okonomibk.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(836): Illuminate\Container\Container->make()
#5 /home/okonomi/okonomibk.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(1419): Illuminate\Foundation\Application->make()
#6 /home/okonomi/okonomibk.com/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(198): Illuminate\Container\Container->offsetGet()
#7 /home/okonomi/okonomibk.com/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(166): Illuminate\Support\Facades\Facade::resolveFacadeInstance()
#8 /home/okonomi/okonomibk.com/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(255): Illuminate\Support\Facades\Facade::getFacadeRoot()
#9 /home/okonomi/okonomibk.com/extensions/igniter/broadcast/vendor/beyondcode/laravel-websockets/src/Dashboard/Http/Middleware/Authorize.php(11): Illuminate\Support\Facades\Facade::__callStatic()
#10 /home/okonomi/okonomibk.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): BeyondCode\LaravelWebSockets\Dashboard\Http\Middleware\Authorize->handle()
#11 /home/okonomi/okonomibk.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#12 /home/okonomi/okonomibk.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(723): Illuminate\Pipeline\Pipeline->then()
#13 /home/okonomi/okonomibk.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(698): Illuminate\Routing\Router->runRouteWithinStack()
#14 /home/okonomi/okonomibk.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\Routing\Router->runRoute()
#15 /home/okonomi/okonomibk.com/vendor/tastyigniter/flame/src/Router/CoreRouter.php(22): Illuminate\Routing\Router->dispatchToRoute()
#16 /home/okonomi/okonomibk.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Igniter\Flame\Router\CoreRouter->dispatch()
#17 /home/okonomi/okonomibk.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#18 /home/okonomi/okonomibk.com/vendor/tastyigniter/flame/src/Setting/Middleware/SaveSetting.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#19 /home/okonomi/okonomibk.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Igniter\Flame\Setting\Middleware\SaveSetting->handle()
#20 /home/okonomi/okonomibk.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#21 /home/okonomi/okonomibk.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#22 /home/okonomi/okonomibk.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TrimStrings->handle()
#23 /home/okonomi/okonomibk.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#24 /home/okonomi/okonomibk.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle()
#25 /home/okonomi/okonomibk.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#26 /home/okonomi/okonomibk.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#27 /home/okonomi/okonomibk.com/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#28 /home/okonomi/okonomibk.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\Cors\HandleCors->handle()
#29 /home/okonomi/okonomibk.com/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#30 /home/okonomi/okonomibk.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\Proxy\TrustProxies->handle()
#31 /home/okonomi/okonomibk.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#32 /home/okonomi/okonomibk.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\Pipeline\Pipeline->then()
#33 /home/okonomi/okonomibk.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#34 /home/okonomi/okonomibk.com/index.php(53): Illuminate\Foundation\Http\Kernel->handle()
#35 {main}
```

**Comment by sampoyigi** [comment]
This issue looks fixed. Closing, but please reopen if it still occurs.
